server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index 503.html;

    # Traefik envía el código de error en el path /{status}.html
    location / {
        try_files $uri /503.html;
    }

    # Sin logs de acceso para no llenar disco
    access_log off;
    error_log /dev/null crit;

    gzip on;
    gzip_types text/html text/css application/javascript;
}
